DROP TABLE #JTB_APV;
DROP TABLE TMP_CUSTOMER_LIFETIME_REPORT;

WITH JOIN_TB AS(
	SELECT F.CRM_Source
		, F.CRM_Channel
		, F.Customer_ID
		, ISNULL(F.TRANS_CNT,0) TRANS_CNT
		, ISNULL(F.TRANS_AMT,0) TRANS_AMT
		, ISNULL(DATEDIFF(DAY,F.FIRST_TRANS,LAST_TRANS)+1,0)  LIFE_SPAN
		, GPM
	FROM FACT_DIGITAL_PROFILES F 
		LEFT JOIN ( SELECT Customer_ID, MAX(Transaction_DT) LAST_TRANS
					FROM DIM_TRANSACTIONS
					GROUP BY Customer_ID
		) T ON F.Customer_ID=T.Customer_ID
		LEFT JOIN GPM G ON G.CRM_Source = F.CRM_Source
--	ORDER BY F.Customer_ID
)
SELECT *, TRANS_AMT/IIF(TRANS_CNT=0,1,TRANS_CNT) APV
INTO #JTB_APV
FROM JOIN_TB;

DECLARE @APFR FLOAT, @CR FLOAT;
SET @APFR = (
			SELECT CAST(SUM(TRANS_CNT) AS FLOAT)/COUNT(DISTINCT Customer_id)
			FROM FACT_DIGITAL_PROFILES
);
SET @CR = (
		SELECT 1-CAST(SUM(IIF(TRANS_CNT>=2,1,0)) AS FLOAT) /COUNT(DISTINCT Customer_ID)
		FROM FACT_DIGITAL_PROFILES
);
SELECT *
	, APV*@APFR CV
	, APV*@APFR*GPM/@CR CLV
INTO TMP_CUSTOMER_LIFETIME_REPORT
FROM #JTB_APV;

WITH DIFF AS (
	SELECT CRM_Source, CRM_Channel
		, AVG(CLV) OVER (PARTITION BY CRM_Source, CRM_Channel) AVG_OF_CLV
		, Customer_ID
		, CLV
		, CLV - AVG(CLV) OVER (PARTITION BY CRM_Source, CRM_Channel) DIFF_TO_AVG
		, RANK() OVER(PARTITION BY CRM_Source ORDER BY CLV DESC) [RANK_BY_SOURCE]
	FROM TMP_CUSTOMER_LIFETIME_REPORT
--	ORDER BY CLV DESC
) 
SELECT CRM_Source, CRM_Channel
	, AVG(DIFF_TO_AVG) AVG_OF_DIFF
FROM DIFF
GROUP BY CRM_Source, CRM_Channel
