--------------------------------------------- 1. Performance of Marketing Campaign--------------------------------------------------------
--- 1.2. The Profit and Lost Balance
-- Profit
DROP TABLE PROFIT_N_LOST_REPORT;
WITH CAL_PROFIT AS (
	SELECT F.CRM_Source
		, F.CRM_Channel
		, TT.Transaction_Group
		, T.Transaction_Amount
		, N.NIM
		, N.NIM*T.Transaction_Amount PROFIT
	FROM DIM_TRANSACTIONS T 
		JOIN  DIM_TRANSACTION_TYPE TT ON TT.Transaction_Type=T.Transaction_Type
		JOIN  FACT_DIGITAL_PROFILES F ON T.Customer_ID=F.Customer_ID
		JOIN  NIM N ON N.Transaction_Group=TT.Transaction_Group
)
,TOTAL_PROFIT AS (
	SELECT CRM_Source
		, CRM_Channel
		, SUM(PROFIT) TOTAL_PROFIT
	FROM CAL_PROFIT
	GROUP BY CRM_Source, CRM_Channel
)
--- COST
,A AS(
	SELECT CRM.CRM_Source
		, CRM.CRM_Channel
		, IIF(F.FIRST_TRANS IS NOT NULL, 'TRANS',
				(IIF(F.[Account_Created_DT] IS NOT NULL, 'ACC',
					IIF(E.Customer_ID IS NOT NULL, 'CUS',
						IIF(E.eKYC_DT IS NOT NULL , 'EKYC',
							IIF(CRM.Install_App_DT IS NOT NULL, 'INSTALL',
								IIF(CRM.Click_Ads_DT IS NOT NULL,'CLICK',NULL))))))) STAGE
	FROM DIM_CRM CRM
		LEFT JOIN DIM_EKYC E ON CRM.eKYC_ID=E.eKYC_ID
		LEFT JOIN FACT_DIGITAL_PROFILES F ON F.Customer_ID=E.Customer_ID
)
, N AS(
	SELECT CRM_Source
		, CRM_Channel
		, STAGE
		, COUNT(*) CNT
	FROM A
	GROUP BY CRM_Source, CRM_Channel, STAGE
)
, ACQUISITION_COST AS (
SELECT CRM_Source
	, N.CRM_Channel
	, C.Base_Payment_per_month*12 Base_Payment
	, CASE 
		WHEN STAGE ='CLICK' THEN CNT*C.Click
		WHEN STAGE ='INSTALL' THEN CNT*C.Install
		WHEN STAGE ='EKYC' THEN CNT*C.eKYC
		WHEN STAGE ='CUS' THEN CNT*C.Customer
		WHEN STAGE ='ACC' THEN CNT*C.Acc
		WHEN STAGE ='TRANS' THEN CNT*Trans
	END ACQUISITION_COST
FROM N JOIN COST C ON C.CRM_Channel = N.CRM_Channel
)
,TOTAL_COST AS (SELECT DISTINCT CRM_Source
	, CRM_Channel
	, Base_Payment + SUM(ACQUISITION_COST) OVER (PARTITION BY CRM_Source, CRM_Channel) TOTAL_COST
FROM ACQUISITION_COST
)

--- Pofir and Lost report
, CUS_CNT AS(
	SELECT CRM_Source, COUNT(DISTINCT Customer_ID) ACTIVE_CUSTOMERS
	FROM FACT_DIGITAL_PROFILES
	WHERE FIRST_TRANS IS NOT NULL
	GROUP BY CRM_Source
)
SELECT C.CRM_Source
	, C.CRM_Channel
	, TOTAL_PROFIT
	, TOTAL_COST
	, TOTAL_PROFIT-TOTAL_COST NET_PROFIT
	, (TOTAL_PROFIT-TOTAL_COST)*1.0/TOTAL_COST [ROI]
	, ACTIVE_CUSTOMERS
	, TOTAL_COST*1.0/ACTIVE_CUSTOMERS COST_PER_ACTIVE_CUS
	, (TOTAL_PROFIT-TOTAL_COST)*1.0/ACTIVE_CUSTOMERS NET_PROFIT_PER_ACTIVE_CUS
	, (TOTAL_PROFIT-TOTAL_COST)*1.0/TOTAL_PROFIT GROSS_PROFIT_MAGIN
INTO PROFIT_N_LOST_REPORT
FROM TOTAL_COST C JOIN TOTAL_PROFIT P ON P.CRM_Source=C.CRM_Source 
	JOIN CUS_CNT CNT ON CNT.CRM_Source=C.CRM_Source
ORDER BY C.CRM_Source

DROP TABLE GPM;
SELECT CRM_Source, CRM_Channel, GROSS_PROFIT_MAGIN GPM
INTO GPM
FROM PROFIT_N_LOST_REPORT

SELECT * FROM PROFIT_N_LOST_REPORT