--WITH K AS 
--(
--	SELECT DISTINCT CONVERT(VARCHAR(6),EKYC_DT,112) eKYC_MONTH
--	FROM FACT_DIGITAL_PROFILES
--)

--,N AS(
--	SELECT DISTINCT CONVERT(VARCHAR(6),EKYC_DT,112) eKYC_MONTH
--		, SUM(IIF(Fraud_Type = 'FRAUD' AND Account_Status <> 'CLOSED',1,0)) OVER() FRAUD_NOT_CLOSED 
--		, SUM(IIF(Fraud_Type = 'RISK' AND Account_Status <> 'SUSPENDED',1,0)) OVER() RISK_NOT_SUSPENDED
--		, SUM(IIF(Fraud_Type = 'CHECKED' AND Account_Status <> 'ACTIVE',1,0)) OVER() CHECK_NOT_ACTIVE
--	FROM FACT_DIGITAL_PROFILES F JOIN DIM_TRANSACTIONS T
--	ON F.Account_Number=T.Account_Number
--), FRAUD_TRANS AS(
--	SELECT CONVERT(VARCHAR(6),EKYC_DT,112) eKYC_MONTH
--		,COUNT(TRANSACTION_ID) FRAUD_TRANS
--		--, SUM(T.Transaction_Amount) TOTAL_AMOUNT
--	FROM FACT_DIGITAL_PROFILES F JOIN DIM_TRANSACTIONS T
--	ON F.Account_Number=T.Account_Number
--	WHERE F.Fraud_Type ='FRAUD'
--	AND T.Transaction_DT>=PosteKYC_created_DT
--	GROUP BY CONVERT(VARCHAR(6),EKYC_DT,112)
--), RISK_TRANS AS(
--	SELECT CONVERT(VARCHAR(6),EKYC_DT,112) eKYC_MONTH
--		,COUNT(TRANSACTION_ID) RISK_TRANS
--		--, SUM(T.Transaction_Amount) TOTAL_AMOUNT
--	FROM FACT_DIGITAL_PROFILES F JOIN DIM_TRANSACTIONS T
--	ON F.Account_Number=T.Account_Number
--	JOIN DIM_TRANSACTION_TYPE TT ON T.Transaction_Type=TT.Transaction_Type
--	WHERE F.Fraud_Type ='RISK'
--	AND T.Transaction_DT>=PosteKYC_created_DT
--	AND TT.Transaction_Group='DEPOSIT'
--	GROUP BY CONVERT(VARCHAR(6),EKYC_DT,112)
--)
--SELECT N.eKYC_MONTH
--	, FRAUD_NOT_CLOSED
--	, RISK_NOT_SUSPENDED
--	, CHECK_NOT_ACTIVE
--	, ISNULL(R.RISK_TRANS,0) + (ISNULL(F.FRAUD_TRANS,0)) TOTAL_RISK_FRAUD_TRANS
--	--, R.RISK_TRANS
--	--, F.FRAUD_TRANS
--	--, R.TOTAL_AMOUNT + F.TOTAL_AMOUNT TOTAL_AMOUNT
--FROM K LEFT JOIN FRAUD_TRANS F ON F.eKYC_MONTH=K.eKYC_MONTH
--LEFT JOIN RISK_TRANS R ON R.eKYC_MONTH=K.eKYC_MONTH
--LEFT JOIN N ON N.eKYC_MONTH=K.eKYC_MONTH
--ORDER BY TOTAL_RISK_FRAUD_TRANS

--DETAIL
SELECT CONVERT(VARCHAR(6),EKYC_DT,112) eKYC_MONTH
		, F.Customer_ID
		, IIF(Fraud_Type = 'FRAUD' AND Account_Status <> 'CLOSED',1,0) FRAUD_NOT_CLOSED 
		, IIF(Fraud_Type = 'RISK' AND Account_Status <> 'SUSPENDED',1,0) RISK_NOT_SUSPENDED
		, IIF(Fraud_Type = 'CHECKED' AND Account_Status <> 'ACTIVE',1,0) CHECK_NOT_ACTIVE
		, IIF(FRAUD_TRANS.Account_Number IS NOT NULL,1,0) FRAUD_TRANS
		, FRAUD_TRANS_ID
		, FRAUD_TRANS_AMOUNT
		, FRAUD_TRANS_GROUP
		, FRAUD_TRANS_RANGE
		, IIF(RISK_TRANS.Account_Number IS NOT NULL,1,0) RISK_TRANS
		, RISK_TRANS_ID
		, RISK_TRANS_AMOUNT
		, RISK_TRANS_GROUP
		, RISK_TRANS_RANGE
	FROM FACT_DIGITAL_PROFILES F 	
	LEFT JOIN (
		SELECT F.Customer_ID
			, T.Transaction_ID FRAUD_TRANS_ID
			, T.Account_Number
			, T.Transaction_Amount FRAUD_TRANS_AMOUNT
			, TT.Transaction_Group FRAUD_TRANS_GROUP
			, T.Transaction_Range FRAUD_TRANS_RANGE 
		FROM DIM_TRANSACTIONS T LEFT JOIN FACT_DIGITAL_PROFILES F ON F.Account_Number=T.Account_Number
		LEFT JOIN DIM_TRANSACTION_TYPE TT ON TT.Transaction_Type=T.Transaction_Type
		WHERE T.Transaction_DT>=F.PosteKYC_created_DT 
			AND F.Fraud_Type='FRAUD'
	) FRAUD_TRANS ON F.Account_Number=FRAUD_TRANS.Account_Number
	LEFT JOIN (
		SELECT F.Customer_ID
			, T.Transaction_ID RISK_TRANS_ID
			, T.Account_Number
			, T.Transaction_Type RISK_TRANS_AMOUNT
			, TT.Transaction_Group RISK_TRANS_GROUP
			, T.Transaction_Range RISK_TRANS_RANGE 
		FROM DIM_TRANSACTIONS T LEFT JOIN FACT_DIGITAL_PROFILES F ON F.Account_Number=T.Account_Number
		LEFT JOIN DIM_TRANSACTION_TYPE TT ON TT.Transaction_Type=T.Transaction_Type
		WHERE T.Transaction_DT>=F.PosteKYC_created_DT 
			AND TT.Transaction_Group='DEPOSIT'
			AND F.Fraud_Type='RISK'
	) RISK_TRANS ON F.Account_Number=RISK_TRANS.Account_Number